<a href="https://colab.research.google.com/github/Homaoa/Classification-of-a-Bank-Marketing-Data-Set/blob/main/Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [59]:
url='/content/bank_marketing_cleaned_data.csv'
df=pd.read_csv(url)
df.head()

Unnamed: 0  Age          Job  ... Euribor3m Nr_employed Decision
0           0   56  "housemaid"  ...     4.857      5191.0     "no"
1           1   57   "services"  ...     4.857      5191.0     "no"
2           2   37   "services"  ...     4.857      5191.0     "no"
3           3   40     "admin."  ...     4.857      5191.0     "no"
4           4   56   "services"  ...     4.857      5191.0     "no"

[5 rows x 21 columns]

In [ ]:
#In EDA part, I have found the variables that are the best choices for developing the model

In [60]:
df_model=df[['Job','Marital','Education','Default','Contact','Month','Day','Pdays','Poutcome','Nr_employed', 'Euribor3m', 'Emp_var_rate', 'Previous', 'Cons_price_idx','Decision']]

In [ ]:
#Because I uploaded the data again in this new colab page, python used its own defualts for the type of the variables
#So I have to change the type of Pdays again

In [ ]:
df_model['Pdays']=df_model['Pdays'].astype('object')

In [62]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41187 entries, 0 to 41186
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Job             41187 non-null  object 
 1   Marital         41187 non-null  object 
 2   Education       41187 non-null  object 
 3   Default         41187 non-null  object 
 4   Contact         41187 non-null  object 
 5   Month           41187 non-null  object 
 6   Day             41187 non-null  object 
 7   Pdays           41187 non-null  object 
 8   Poutcome        41187 non-null  object 
 9   Nr_employed     41187 non-null  float64
 10  Euribor3m       41187 non-null  float64
 11  Emp_var_rate    41187 non-null  float64
 12  Previous        41187 non-null  int64  
 13  Cons_price_idx  41187 non-null  float64
 14  Decision        41187 non-null  object 
dtypes: float64(4), int64(1), object(10)
memory usage: 4.7+ MB


In [63]:
X=df_model[['Job','Marital','Education','Default','Contact','Month','Day','Pdays','Poutcome','Nr_employed', 'Euribor3m', 'Emp_var_rate', 'Previous', 'Cons_price_idx']]
y=df_model[['Decision']]

In [ ]:
#Now the categorical variables should be dummies

In [64]:
X = pd.get_dummies(X)

In [65]:
X.head()

Nr_employed  Euribor3m  ...  Poutcome_"nonexistent"  Poutcome_"success"
0       5191.0      4.857  ...                       1                   0
1       5191.0      4.857  ...                       1                   0
2       5191.0      4.857  ...                       1                   0
3       5191.0      4.857  ...                       1                   0
4       5191.0      4.857  ...                       1                   0

[5 rows x 79 columns]

In [ ]:
#Now I split the data into train and test

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
#After spliting, I scale the numeric variables which are the first 5 variables
#I fit the scaling with train data, and for test data I only transform

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[['Nr_employed','Euribor3m','Emp_var_rate','Previous','Cons_price_idx']]=sc.fit_transform(X_train[['Nr_employed','Euribor3m','Emp_var_rate','Previous','Cons_price_idx']])
X_test[['Nr_employed','Euribor3m','Emp_var_rate','Previous','Cons_price_idx']]=sc.transform(X_test[['Nr_employed','Euribor3m','Emp_var_rate','Previous','Cons_price_idx']])

In [ ]:
### Logistic regression model

In [68]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [69]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[9026  120]
 [ 897  254]]


0.9012333689424105

In [52]:
### KNN model

In [70]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [71]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[8840  306]
 [ 834  317]]


0.8892881421773332

In [55]:
### SVM model

In [72]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [73]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[9038  108]
 [ 927  224]]


0.8994852869767893

In [ ]:
### Kernel SVM model

In [74]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [75]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[9011  135]
 [ 851  300]]


0.904243954549869

In [ ]:
### Naive bayes model

In [76]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [77]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[8808  338]
 [ 786  365]]


0.8908419928134408

In [ ]:
### Decision tree classificatio model

In [78]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [79]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[8721  425]
 [ 805  346]]


0.8805477323492279

In [ ]:
### Random forest classification model

In [80]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [81]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[8834  312]
 [ 821  330]]


0.8899679518306303

In [ ]:
###### Result : as we can see, Kernel SVM model has the best performance with accuracy score = 0.904243954549869
######          after that, it is Logistic regression model with accuracy score = 0.9012333689424105